<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWpdyxme\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWpdyxme/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerWpdyxme.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerWpdyxme\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerWpdyxme\appProdProjectContainer([
    'container.build_hash' => 'Wpdyxme',
    'container.build_id' => 'ba817725',
    'container.build_time' => 1608801128,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWpdyxme');
